# Generated by Django 4.1.4 on 2023-01-03 15:00

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="text",
            field=martor.models.MartorField(),
        ),
    ]
