# Generated by Django 4.1.4 on 2023-01-08 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_userresponse_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresponse",
            name="time_create",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
